package org.zyq.qq.model;

import org.zyq.qq.model.base.BaseService;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Service extends BaseService<Service> {
	public static final Service dao = new Service();
}
